// Generated by scripts/slice-pixel-knight-v7-village-cutouts.py
export type StarterVillageV7AtomId =
  | "atom-0000"
  | "atom-0004"
  | "atom-0001"
  | "atom-0002"
  | "atom-0003"
  | "atom-0007"
  | "atom-0014"
  | "atom-0006"
  | "atom-0018"
  | "atom-0005"
  | "atom-0020"
  | "atom-0021"
  | "atom-0015"
  | "atom-0009"
  | "atom-0008"
  | "atom-0016"
  | "atom-0028"
  | "atom-0046"
  | "atom-0029"
  | "atom-0017"
  | "atom-0048"
  | "atom-0019"
  | "atom-0022"
  | "atom-0024"
  | "atom-0050"
  | "atom-0030"
  | "atom-0023"
  | "atom-0049"
  | "atom-0041"
  | "atom-0039"
  | "atom-0045"
  | "atom-0040"
  | "atom-0025"
  | "atom-0026"
  | "atom-0047"
  | "atom-0031"
  | "atom-0044"
  | "atom-0010"
  | "atom-0013"
  | "atom-0011"
  | "atom-0012"
  | "atom-0043"
  | "atom-0032"
  | "atom-0027"
  | "atom-0042"
  | "atom-0051"
  | "atom-0033"
  | "atom-0034"
  | "atom-0035"
  | "atom-0036"
  | "atom-0037"
  | "atom-0038"

import atom_0000Url from './atom-0000.png'
import atom_0004Url from './atom-0004.png'
import atom_0001Url from './atom-0001.png'
import atom_0002Url from './atom-0002.png'
import atom_0003Url from './atom-0003.png'
import atom_0007Url from './atom-0007.png'
import atom_0014Url from './atom-0014.png'
import atom_0006Url from './atom-0006.png'
import atom_0018Url from './atom-0018.png'
import atom_0005Url from './atom-0005.png'
import atom_0020Url from './atom-0020.png'
import atom_0021Url from './atom-0021.png'
import atom_0015Url from './atom-0015.png'
import atom_0009Url from './atom-0009.png'
import atom_0008Url from './atom-0008.png'
import atom_0016Url from './atom-0016.png'
import atom_0028Url from './atom-0028.png'
import atom_0046Url from './atom-0046.png'
import atom_0029Url from './atom-0029.png'
import atom_0017Url from './atom-0017.png'
import atom_0048Url from './atom-0048.png'
import atom_0019Url from './atom-0019.png'
import atom_0022Url from './atom-0022.png'
import atom_0024Url from './atom-0024.png'
import atom_0050Url from './atom-0050.png'
import atom_0030Url from './atom-0030.png'
import atom_0023Url from './atom-0023.png'
import atom_0049Url from './atom-0049.png'
import atom_0041Url from './atom-0041.png'
import atom_0039Url from './atom-0039.png'
import atom_0045Url from './atom-0045.png'
import atom_0040Url from './atom-0040.png'
import atom_0025Url from './atom-0025.png'
import atom_0026Url from './atom-0026.png'
import atom_0047Url from './atom-0047.png'
import atom_0031Url from './atom-0031.png'
import atom_0044Url from './atom-0044.png'
import atom_0010Url from './atom-0010.png'
import atom_0013Url from './atom-0013.png'
import atom_0011Url from './atom-0011.png'
import atom_0012Url from './atom-0012.png'
import atom_0043Url from './atom-0043.png'
import atom_0032Url from './atom-0032.png'
import atom_0027Url from './atom-0027.png'
import atom_0042Url from './atom-0042.png'
import atom_0051Url from './atom-0051.png'
import atom_0033Url from './atom-0033.png'
import atom_0034Url from './atom-0034.png'
import atom_0035Url from './atom-0035.png'
import atom_0036Url from './atom-0036.png'
import atom_0037Url from './atom-0037.png'
import atom_0038Url from './atom-0038.png'

export const starterVillageV7Atoms = [
  { id: "atom-0000" as const, src: atom_0000Url, width: 306, height: 302 },
  { id: "atom-0004" as const, src: atom_0004Url, width: 303, height: 295 },
  { id: "atom-0001" as const, src: atom_0001Url, width: 284, height: 277 },
  { id: "atom-0002" as const, src: atom_0002Url, width: 260, height: 267 },
  { id: "atom-0003" as const, src: atom_0003Url, width: 260, height: 263 },
  { id: "atom-0007" as const, src: atom_0007Url, width: 178, height: 163 },
  { id: "atom-0014" as const, src: atom_0014Url, width: 149, height: 130 },
  { id: "atom-0006" as const, src: atom_0006Url, width: 78, height: 175 },
  { id: "atom-0018" as const, src: atom_0018Url, width: 116, height: 142 },
  { id: "atom-0005" as const, src: atom_0005Url, width: 78, height: 175 },
  { id: "atom-0020" as const, src: atom_0020Url, width: 114, height: 140 },
  { id: "atom-0021" as const, src: atom_0021Url, width: 112, height: 138 },
  { id: "atom-0015" as const, src: atom_0015Url, width: 104, height: 105 },
  { id: "atom-0009" as const, src: atom_0009Url, width: 154, height: 96 },
  { id: "atom-0008" as const, src: atom_0008Url, width: 149, height: 96 },
  { id: "atom-0016" as const, src: atom_0016Url, width: 98, height: 168 },
  { id: "atom-0028" as const, src: atom_0028Url, width: 119, height: 96 },
  { id: "atom-0046" as const, src: atom_0046Url, width: 104, height: 78 },
  { id: "atom-0029" as const, src: atom_0029Url, width: 111, height: 96 },
  { id: "atom-0017" as const, src: atom_0017Url, width: 90, height: 157 },
  { id: "atom-0048" as const, src: atom_0048Url, width: 108, height: 68 },
  { id: "atom-0019" as const, src: atom_0019Url, width: 80, height: 145 },
  { id: "atom-0022" as const, src: atom_0022Url, width: 82, height: 141 },
  { id: "atom-0024" as const, src: atom_0024Url, width: 82, height: 107 },
  { id: "atom-0050" as const, src: atom_0050Url, width: 97, height: 67 },
  { id: "atom-0030" as const, src: atom_0030Url, width: 96, height: 81 },
  { id: "atom-0023" as const, src: atom_0023Url, width: 76, height: 135 },
  { id: "atom-0049" as const, src: atom_0049Url, width: 86, height: 66 },
  { id: "atom-0041" as const, src: atom_0041Url, width: 60, height: 80 },
  { id: "atom-0039" as const, src: atom_0039Url, width: 58, height: 83 },
  { id: "atom-0045" as const, src: atom_0045Url, width: 63, height: 69 },
  { id: "atom-0040" as const, src: atom_0040Url, width: 57, height: 80 },
  { id: "atom-0025" as const, src: atom_0025Url, width: 63, height: 116 },
  { id: "atom-0026" as const, src: atom_0026Url, width: 65, height: 87 },
  { id: "atom-0047" as const, src: atom_0047Url, width: 59, height: 63 },
  { id: "atom-0031" as const, src: atom_0031Url, width: 78, height: 66 },
  { id: "atom-0044" as const, src: atom_0044Url, width: 54, height: 73 },
  { id: "atom-0010" as const, src: atom_0010Url, width: 44, height: 100 },
  { id: "atom-0013" as const, src: atom_0013Url, width: 44, height: 99 },
  { id: "atom-0011" as const, src: atom_0011Url, width: 43, height: 98 },
  { id: "atom-0012" as const, src: atom_0012Url, width: 43, height: 98 },
  { id: "atom-0043" as const, src: atom_0043Url, width: 51, height: 70 },
  { id: "atom-0032" as const, src: atom_0032Url, width: 68, height: 60 },
  { id: "atom-0027" as const, src: atom_0027Url, width: 53, height: 96 },
  { id: "atom-0042" as const, src: atom_0042Url, width: 48, height: 67 },
  { id: "atom-0051" as const, src: atom_0051Url, width: 49, height: 52 },
  { id: "atom-0033" as const, src: atom_0033Url, width: 52, height: 46 },
  { id: "atom-0034" as const, src: atom_0034Url, width: 47, height: 42 },
  { id: "atom-0035" as const, src: atom_0035Url, width: 44, height: 41 },
  { id: "atom-0036" as const, src: atom_0036Url, width: 39, height: 35 },
  { id: "atom-0037" as const, src: atom_0037Url, width: 36, height: 32 },
  { id: "atom-0038" as const, src: atom_0038Url, width: 29, height: 25 },
] as const

